spring.application.name=EMPLOYEE
server.port=8081

spring.datasource.url = jdbc:mysql://localhost:3306/
spring.datasource.username = root
spring.datasource.password = 66669999

spring.jpa.hibernate.ddl-auto = update
